# -*- coding: utf-8 -*-
"""STOCK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zY0CCyuBGUdqX8lK1b4CS0cQq023R3kg
"""

import pandas as pd
import numpy as np

data = pd.read_csv('IRFC_120D_CSV.csv')

data.head()

"""**PLOT THE HISTOGRAM**"""

import matplotlib.pyplot as plt

time_intervals = data['TF']

color_1 = '#0abb92'
color_2 = '#d55438'

width_1 = 0.4
width_2 = 0.03

gain = data[data['CLOSE']>=data['OPEN']]

loss = data[data['CLOSE']<data['OPEN']]

gain.head()

loss.head()

"""**GAIN - BODY**"""

plt.bar(gain['TF'],gain['CLOSE']-gain['OPEN'],width_1,bottom=gain['OPEN'],color=color_1)

"""**LOSS - BODY**"""

plt.bar(loss['TF'],loss['OPEN']-loss['CLOSE'],width_1,bottom=loss['CLOSE'],color=color_2)

"""**COMBINED GAIN & LOSS BODY**"""

plt.bar(gain['TF'],gain['CLOSE']-gain['OPEN'],width_1,bottom=gain['OPEN'],color=color_1)
plt.bar(loss['TF'],loss['OPEN']-loss['CLOSE'],width_1,bottom=loss['CLOSE'],color=color_2)

"""**GAIN - HIGHEST & LOWEST**"""

plt.bar(gain['TF'],gain['HIGHEST']-gain['CLOSE'],width_2,bottom=gain['CLOSE'],color=color_1)
plt.bar(gain['TF'],gain['OPEN']-gain['LOWEST'],width_2,bottom=gain['LOWEST'],color=color_2)

"""**LOSS - HIGHEST & LOWEST**"""

plt.bar(loss['TF'],loss['CLOSE']-loss['LOWEST'],width_2,bottom=loss['LOWEST'],color=color_2)
plt.bar(loss['TF'],loss['HIGHEST']-loss['OPEN'],width_2,bottom=loss['OPEN'],color=color_1)

# color
plt.figure(facecolor='#121212')
ax = plt.axes()
ax.set_facecolor("#121212")

axis = plt.gca()
ax.spines['bottom'].set_color('white')
ax.spines['bottom'].set_linewidth(0.5)
ax.spines['left'].set_color('#121212')
ax.spines['top'].set_color('#121212')
ax.spines['right'].set_color('#121212')

ax.tick_params(axis='x', colors='white')
ax.tick_params(axis='y', colors='white')

#labels
plt.title("IRFC  22 NOV - 22 MAR (DATA MAY BE INCORRECT) ",color='white')
plt.xlabel("Interval-1D",color='white')
plt.ylabel("STOCK-PRICES",color='white')

# candle - body
plt.bar(gain['TF'],gain['CLOSE']-gain['OPEN'],width_1,bottom=gain['OPEN'],color=color_1)
plt.bar(loss['TF'],loss['OPEN']-loss['CLOSE'],width_1,bottom=loss['CLOSE'],color=color_2)

# candle - gain
plt.bar(gain['TF'],gain['HIGHEST']-gain['CLOSE'],width_2,bottom=gain['CLOSE'],color=color_1)
plt.bar(gain['TF'],gain['OPEN']-gain['LOWEST'],width_2,bottom=gain['LOWEST'],color=color_1)

# candle - loss
plt.bar(loss['TF'],loss['CLOSE']-loss['LOWEST'],width_2,bottom=loss['LOWEST'],color=color_2)
plt.bar(loss['TF'],loss['HIGHEST']-loss['OPEN'],width_2,bottom=loss['OPEN'],color=color_2)